# Generated by Django 4.2 on 2025-04-15 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='_state',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Disabled', 'Disabled')], default='Active', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='Untagged', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
